config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/daily-log", to: "logs#daily_log"
  get "/weekly-log", to: "logs#weekly_log"
  get "/monthly-log", to: "logs#monthly_log"
  get "/future-log", to: "logs#future_log"
  get "/users/profile", to: "pages#profile"
  get "/meet-the-team", to: "pages#meet_the_team"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    resources :subtasks
  end
  resources :journal_entries, path: "journal-entries"
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user
  has_many :journal_categories
  has_many :categories, through: :journal_categories

  validates :title, :entry, length: { minimum: 2 }
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: %i[ show edit update destroy ]

  def index
    if current_user.admin?
      @journal_entries = policy_scope(JournalEntry).order(user_id: :asc)
    else
      @journal_entries = policy_scope(JournalEntry).where(user_id: current_user)
    end
  end

  def show
    authorize @journal_entry
  end

  def new
    @journal_entry = JournalEntry.new
    @journal_entry.user = current_user
    authorize @journal_entry
  end

  def edit
    authorize @journal_entry
  end

  def create
    @journal_entry = JournalEntry.new(journal_entry_params)
    @journal_entry.user = current_user
    authorize @journal_entry

    if @journal_entry.save!
      redirect_to @journal_entry, notice: "JournalEntry #{@journal_entry.title} was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @journal_entry
    if @journal_entry.update!(journal_entry_params)
      redirect_to @journal_entry, notice: "JournalEntry #{@journal_entry.title} was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @journal_entry
    title = @journal_entry.title
    @journal_entry.categories.destroy_all
    @journal_entry.destroy
    redirect_to journal_entries_path, notice: "JournalEntry #{title} was successfully destroyed."
  end

  private

  def journal_entry_params
    params.require(:journal_entry).permit(:title, :entry, :created_at, :updated_at, :user_id)
  end

  def set_journal_entry
    @journal_entry = JournalEntry.find(params[:id])
  end
end

app/views/journal_entries/_form.html.erb
<%= simple_form_for(journal_entry, html: { data: { controller: "form" }, class: "m-2 p-3 mx-auto" }) do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :title, input_html: { class: "form-control mb-3" } %>

    <%= f.input :entry, as: :text, input_html: { class: "form-control mb-3", 'rows' => 5, 'cols' => 10 } %>

    <%= f.input :created_at, readonly: true, html5: true, input_html: { class: "form-control mb-3" } %>

    <%= f.input :updated_at, readonly: true, html5: true, input_html: { class: "form-control mb-3" } %>

  </div>

  <div class="form-actions links d-flex justify-content-end align-items-center">

    <%= render 'links', journal_entry: journal_entry %>

    <%= button_tag type: 'submit', class: "btn btn-primary" do %>

      <%# <i class="fa-solid fa-thumbs-up"></i> %>

      <i class="fa-solid fa-circle-check"></i> Done

    <% end %>

  </div>

<% end %>

app/views/journal_entries/_links.html.erb
<%= link_to :back, class: "btn btn-success m-1", title: "Back button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>

<% if action_name != "index" %>
  <%= link_to journal_entries_path, class: "btn btn-secondary m-1", title: "Back to all journal entries" do %>
    <i class="fa-solid fa-list-check"></i>
  <% end %>
<% end %>

<% if journal_entry.persisted? %>

  <%# <%= link_to "Create a category", new_category_path(journal_entry), class: "btn btn-primary m-1" %>
  <%# <%= link_to new_task_subtask_path(task), class: "btn btn-primary m-1", title: "Add a task?" do %>
    <%# <i class="fa-solid fa-square-plus"></i> %>
  <%# <% end %>

  <% if policy(journal_entry).edit? %>

    <%= link_to edit_journal_entry_path(journal_entry), class: "btn btn-warning m-1", title: "Edit this log" do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>

  <% end %>

  <% if policy(journal_entry).destroy? %>
    <%= link_to  journal_entry_path(journal_entry), class: "btn btn-danger m-1", title: "Delete this log?", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
  <% end %>

<% end %>

app/views/journal_entries/edit.html.erb
<div class="d-flex justify-content-center align-items-start min-vh-100">

  <div class="col-md-10 p-3">

    <h1 class="my-5 mb-3 fst-bold text-center">Edit Journal Entry</h1>

    <%= render 'form', journal_entry: @journal_entry %>

  </div>

</div>

app/views/journal_entries/index.html.erb
<div class="d-flex justify-content-center align-items-start min-vh-100">

  <div class="col-md-10 p-3">

    <% img_url = current_user.admin? ? current_user.image_url : @journal_entries.first.user.image_url %>

    <%= image_tag img_url, class: "rounded-circle my-2" %>

    <div class="header d-flex justify-content-between align-items-center">

      <h1 class="my-5 mb-3 fst-bold">All Journal Entries</h1>

      <%= link_to new_journal_entry_path, class: "btn bg-quinary btn-lg", title: "Add a new journal entry?" do %>
        <i class="fa-solid fa-square-plus"></i>
      <% end %>

    </div>

    <hr>

    <% @journal_entries.each do |journal_entry| %>

      <h2><%= journal_entry.title %><h2>



      <p class="bd-font"><%= journal_entry.entry %></p>

      <div class="links d-flex justify-content-end align-items-center">

        <%= render 'links', journal_entry: journal_entry %>

      </div>

      <hr>

      <div class="categories">

        <% if journal_entry.categories.count > 0 %>

          <% journal_entry.categories.each do |category| %>

            <h4>#<%= category.category %><h4>

            <%# <%= render 'categories/links', category: category %>

            <hr>

          <% end %>

        <% end %>

      </div>

      <hr>

    <% end %>

  </div>

</div>

app/views/journal_entries/new.html.erb
<div class="d-flex justify-content-center align-items-start min-vh-100">

  <div class="col-md-10 p-3">

    <h1 class="my-5 mb-3 fst-bold text-center">Add New Entry</h1>

    <%= render 'form', journal_entry: @journal_entry %>

  </div>

</div>

app/views/journal_entries/show.html.erb
<div class="d-flex justify-content-center align-items-start min-vh-100">

  <div class="col-md-10 p-3">

    <h1><%= @journal_entry.title %></h1>

    <h3>- <%= @journal_entry.user.full_name %></h3>

    <p><%= @journal_entry.entry %></p>

    <div class="links">

      <%= render 'links', journal_entry: @journal_entry %>

    </div>

  </div>

</div>