config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/daily-log", to: "logs#daily_log"
  get "/weekly-log", to: "logs#weekly_log"
  get "/monthly-log", to: "logs#monthly_log"
  get "/future-log", to: "logs#future_log"
  get "/users/profile", to: "pages#profile"
  get "/meet-the-team", to: "pages#meet_the_team"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    resources :subtasks
  end
  resources :journal_entries, path: "journal-entries"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :subtasks, inverse_of: :task, dependent: :destroy

  attribute :duration, :duration

  store_accessor :recurs_on, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday

  accepts_nested_attributes_for :subtasks, reject_if: proc { |attributes| attributes["title"].blank? || attributes["_destroy"] == "1" }, allow_destroy: true

  before_save :hms_to_duration

  after_find do |task|
    # p task.duration.class, task.duration
  end

  after_initialize :set_default_start_date, if: :new_record?
  after_initialize :update_duration

  NONE_ROUTINE_NAME = :not_recuring

  enum routine: [
    NONE_ROUTINE_NAME,
    :morning,
    :day,
    :evening,
  ]

  enum task_type: [
         :general,
         :event,
         :fitness,
         :admin,
         :work,
         :self_development,
         :spiritual,
         :stoic_exercise,
         :stoic_discipline,
       ]

  default_scope { where(active: true).order(:start_date) } # completed: false ???

  scope :completed, -> { where(completed: true) }
  scope :pending, -> { where(completed: false) }

  scope :filter_by_user_routines, ->(user, routine) { where("user_id = ? AND routine = ?", user.id, routines[routine]) }

  validates :title, :user_id, :start_date, presence: true

  def duration_to_hms
    sec = self.duration.to_i
    "%02d:%02d:%02d" % [sec / 3600, sec / 60 % 60, sec % 60]
  end

  def hms_to_duration
    if /^\d{2}:\d{2}:\d{2}?$/.match(self.duration.to_s)
      self.duration = ActiveSupport::Duration.build(self.duration.split(":").map(&:to_i).inject(0) { |a, b| a * 60 + b })
    end
  end

  def update_duration
    if self.subtasks.any?
      self.duration = self.subtasks.pluck(:duration).map { |duration| ActiveSupport::Duration.build(duration.to_i) }.sum
    end
  end

  def routine?
    self.routine != NONE_ROUTINE_NAME.to_s
  end

  def self.transform_routines_for_html_select
    self.routines.each_with_object({}) { |(item, index), r| r[item.gsub("_", " ").titleize] = item }
  end

  def self.transform_task_types_for_html_select
    self.task_types.each_with_object({}) { |(item, index), t| t[item.gsub("_", " ").titleize] = item }
  end

  def clone_for_next_occurence
    # Stoic Exercise Routine - will be the only ones with AI generated feedback
    is_stoic_exercise_routine = self.task_type == "stoic_exercise"
    # Clone the task
    new_task = self.dup
    # Clear out user's comments and any AI generated feedback
    new_task.comment = ""
    new_task.ai_feedback = ""
    new_task.completed = false
    # Set the new task to the next occurence
    # Need to work out when the next occurence is...
    new_task.start_date = self.find_next_occurence
    # Save the newly cloned task
    new_task.save!
    # Clone the subtasks if they exist
    self.subtasks.each do |subtask|
      new_subtask = subtask.dup
      new_subtask.task = new_task
      new_subtask.completed = false
      # AI generated feedback
      new_subtask.comment = ""
      new_subtask.ai_feedback = ""
      new_subtask.save!
    end
  end

  private

  def set_default_start_date
    self.start_date = Time.now if self.start_date.nil?
  end

  def find_next_occurence
    # Need to work out when the next occurence is...
    time = self.start_date.strftime("%H:%M")
    date = Time.now.strftime("%d-%m-%Y")
    today = Time.parse("#{date} #{time}")
    7.times do |i|
      j = i + 1
      the_date = today + j.day
      this_day = eval("self.#{(the_date).strftime("%A").downcase}")
      # Was originally actual boolean values, but the frontend
      # has switched to a string value of "1" or "0" ???
      if this_day.class == String && this_day == "1" || this_day.class == Integer && this_day == 1
        return the_date
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_dynamic_routine_turbo_frame_id, except: %i[ edit update ]

  def index
    if has_valid_routine?
      @tasks = policy_scope(Task).where(user: current_user, routine: params[:routine])
    else
      @tasks = policy_scope(Task).where(user: current_user, routine: Task::NONE_ROUTINE_NAME)
    end
  end

  def show
    authorize @task
  end

  def new
    if has_valid_routine?
      routine = params[:routine].is_a?(Array) ? Task::NONE_ROUTINE_NAME : params[:routine].to_sym
      @task = Task.new(routine: routine, user: current_user)
    else
      @task = Task.new(user: current_user)
      # Not needed as the form will create the subtasks via + <button>
      # @task.subtasks.build
    end
    authorize @task
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    authorize @task
    respond_to do |format|
      if @task.save
        if (request.referer.include?("log"))
          path = request.referer
        else
          path = @task.routine? ? tasks_path(routine: @task.routine) : tasks_path
        end
        format.html { redirect_to path, notice: "Task, #{@task.title}, created successfully with #{@task.subtasks.count} sub tasks!", status: :see_other }
        format.json do
          resp = {
            status: "success",
            task: @task,
            errors: "",
            message: "Task, #{@task.title}, created successfully with #{@task.subtasks.count} sub tasks!",
          }
          render json: resp.to_json, notice: "Task, #{@task.title}, created successfully with #{@task.subtasks.count} sub tasks!", status: :see_other # :ok for AJAX when needed
        end
      else
        format.html { render :new, alert: "Could not create task #{@task.title}", status: :unprocessable_entity }
        format.json do
          resp = {
            status: "error",
            task: @task,
            errors: @task.errors,
            message: "Task NOT created!",
          }
          render json: resp.to_json, alert: "Could not create task #{@task.title}", status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    authorize @task
    if request.headers["Content-Type"] == "application/json" || request.headers["Accept"] == "application/json"
      render json: {
        form: render_to_string(partial: "tasks/form", formats: [:html], locals: { task: @task }),
        status: "success",
        message: "Form ready to be edited.",
      }
    else
      render :edit, task: @task, notice: "Task, #{@task.title}, with #{@task.subtasks.count} sub tasks ready for updating!", status: :see_other
    end
  end

  def update
    authorize @task
    respond_to do |format|
      if @task.update(task_params)
        # Check for routines and if so, are they completed?
        # If completed, clone for the next occurence
        if @task.routine? && @task.completed? && @task.active?
          @task.clone_for_next_occurence
          @task.active = false
          @task.save!
        end
        path = @task.routine? ? tasks_path(routine: @task.routine) : tasks_path
        format.html { redirect_to path, notice: "Task, #{@task.title}, updated successfully with #{@task.subtasks.count} sub tasks!", status: :see_other }
        format.json do
          resp = {
            status: "success",
            task: @task,
            errors: "",
            message: "Task, #{@task.title}, successfully updated with #{@task.subtasks.count} sub tasks!",
          }
          render json: resp.to_json, notice: "Task, #{@task.title}, successfully updated with #{@task.subtasks.count} sub tasks!", status: :ok # :ok for AJAX
        end
      else
        format.html { render :edit, alert: "Server error", status: :unprocessable_entity }
        format.json do
          resp = {
            status: "error",
            task: @task,
            errors: @task.errors,
            message: "Task #{@task.title} NOT updated!",
          }
          render json: resp.to_json, alert: "Error task could not be updated", status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    authorize @task
    title = @task.title
    @task.subtasks.destroy_all
    @task.destroy
    respond_to do |format|
      format.turbo_stream
      url = @task.routine? ? tasks_url(routine: @task.routine) : tasks_url
      format.html { redirect_to url, notice: "Task #{title} deleted!", status: :see_other }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :routine,
      :monday,
      :tuesday,
      :wednesday,
      :thursday,
      :friday,
      :saturday,
      :sunday,
      :task_type,
      :title,
      :description,
      :comment,
      :ai_feedback,
      :start_date,
      :duration,
      :end_date,
      :completed,
      :active,
      subtasks_attributes: [
        :id,
        :order,
        :title,
        :description,
        :comment,
        :ai_feedback,
        :duration,
        :end_date,
        :start_date,
        :due_date,
        :completed,
        :_destroy,
      ],
    )
  end

  def has_valid_routine?
    if defined?(params[:routine])
      routine = params[:routine]
      routine.is_a?(Array) ? (Task.routines.keys & routine).any? : Task.routines.include?(routine)
    else
      false
    end
  end

  def set_dynamic_routine_turbo_frame_id
    routine = params[:routine]
    routine_name = routine.is_a?(Array) ? "non_recuring" : routine
    @turbo_frame_id = has_valid_routine? ? "new_#{routine_name}_routine_turbo_frame" : "new_task_turbo_frame"
  end
end

app/views/tasks/_links.html.erb
<%# <%= link_to :back, class: "btn btn-success m-1", title: "Back button" do %>
  <%# <i class="fa-solid fa-angle-left"></i> %>
<%# <% end %>

<% if action_name != "index" %>

  <%= link_to tasks_path, class: "btn btn-secondary m-1", title: "Back to all tasks" do %>

    <i class="fa-solid fa-list-check"></i>

  <% end %>

<% end %>

<% if !task.nil? && task.persisted? %>

  <%= link_to(new_task_subtask_path(task),
    data: {
      turbo_frame: "turbo_new_subtask_for_#{ dom_id task }"
    },
    class: "btn btn-primary m-1",
    title: "Add a subtask?"
  ) do %>

    <i class="fa-solid fa-square-plus"></i>

  <% end %>

  <% if policy(task).edit? %>

    <%= link_to(edit_task_path(task),
      data: { turbo_frame: "edit_#{ dom_id task }" },
      class: "btn btn-warning m-1",
      title: "Edit this task"
    ) do %>

      <i class="fa-solid fa-pen-to-square"></i>

    <% end %>

  <% end %>

  <% if policy(task).destroy? %>

    <%= link_to task_path(task),
      data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      },
      class: "btn btn-danger m-1",
      title: "Delete this task?" do %>

      <i class="fa-solid fa-trash"></i>

    <% end %>

  <% end %>

<% end %>

app/views/tasks/_sub_task_fields.html.erb
<%# :order, :title, :description, :comment, :start_date, :due_date, :completed %>
<div class="sub-task-fields card m-1 p-2">

  <%= f.input :order, input_html: { class: "mb-3" } %>

  <%= f.input :title, input_html: { class: "mb-3" } %>

  <%= f.input :description, as: :text, input_html: { class: "mb-3", 'rows' => 5, 'cols' => 10 } %>

  <%#= f.input :comment, as: :text, input_html: { class: "mb-3", 'rows' => 5, 'cols' => 10 } %>

  <%= f.input :start_date, html5: true, input_html: { class: "mb-3" } %>

  <%= f.input :due_date, html5: true, input_html: { class: "mb-3" } %>

  <%#= f.input :completed, as: :boolean %>

  <div class="subtask-controls d-flex justify-content-end align-items-center">

    <%= link_to_remove_nested(
      f,
      tag_attributes: {
          class: "remove-nested-assoc",
          title: "Remove this subtask"
        },
        link_classes: 'btn btn-sm btn-danger m-1',
        fields_wrapper_selector: '.sub-task-fields'
      ) do %>

      <i class="fa-solid fa-trash"></i>

    <% end %>

  </div>
</div>

app/views/tasks/_subtask_card.html.erb
<%= turbo_frame_tag "edit_#{ dom_id subtask }_for_#{ dom_id subtask.task }",
  refresh: "morph",
  data: {
    sortable_target: 'dragable',
    controller: "subtask",
    subtask_sortable_outlet: "#new_subtask_for_#{ dom_id subtask.task }",
    subtask_task_outlet: ".parent-#{ (dom_id subtask.task).gsub("_", "-") }",
    subtask_url_value: "#{ task_subtask_url(subtask.task, subtask) }",
    subtask_checked_value: "#{ subtask.completed }",
    subtask_start_time_value: subtask.start_date? ? subtask.start_date.strftime("%H:%M") : "",
    subtask_start_date_time_value: subtask.start_date? ? subtask.start_date.strftime("%Y-%m-%d %H:%M") : "",
  },
  class: "dragable-item card subtask subtask-of-#{ (dom_id subtask.task).gsub('_', '-') } #{ subtask.completed ? ' card-checked' : '' }" do %>

  <div data-subtask-target="cardTitle" title="<%= subtask.start_date? ? subtask.start_date.strftime("%A %d %B %Y at %H:%M") : "" %>">

    <div class="card-header d-flex justify-content-between align-items-center">

      <h3 class="card-title d-flex justify-content-between align-items-center flex-grow-1 overflow-fade">

        <span id="<%= "#{dom_id subtask}_order" %>"
          class="order-wrapper pe-2"
          data-subtask-target="ordinal"
          data-action="change->subtask#onOrdinalChange">

          <%= subtask.order %>

        </span>

        <i class="fa-solid fa-grip-vertical handle pe-2" data-action="mousedown->subtask#onHandleGrabbed"></i>

        <span id="<%= "#{dom_id subtask}_checkbox_wrapper" %>"
          class="checkbox-wrapper pe-2"
          data-subtask-target="checkbox">

          <label
            data-subtask-target="fauxCheckbox"
            data-action="click->subtask#onCheckboxClicked"
            for="<%= "#{dom_id subtask}_completed" %>">

            <i data-subtask-target="fauxCheckIcon" class="fa-solid <%= subtask.completed ? "fa-square-check" : "fa-square" %>"></i>

          </label>

          <input id="<%= "#{dom_id subtask}_completed" %>"
            class="checkbox d-none"
            data-subtask-target="realCheckbox"
            type="checkbox"<%= subtask.completed ? " checked" : "" %>>

        </span>

        <span class="start-date-time pe-2<%= subtask.start_date? ? "" : " d-none" %>">

          <input class="d-none" type="text"
            data-subtask-target="startDateTime"
            value="<%= subtask.start_date? ? subtask.start_date.strftime("%Y-%m-%d %H:%M") : "" %>"
          />

          <span
            data-subtask-target="startTime"
            data-action="click->subtask#onStartTimeClick"><%= subtask.start_date? ? subtask.start_date.strftime("%H:%M") : "" %></span>

        </span>

        <span id="<%= "#{dom_id subtask}_title" %>"
          class="title-wrapper pe-2 flex-grow-1"
          contenteditable="true"
          data-subtask-target="title"
          data-action="focus->subtask#onTitleFocus focusout->subtask#onTitleLostFocus">

          <%= subtask.title %>

        </span>

      </h3>

      <div class="controls d-flex justify-content-end">

        <div class="btn-group">
          <button type="button" class="btn btn-xs btn-secondary dropdown-toggle subtask-menu-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
            <i class="fa-solid fa-bars"></i>
          </button>
          <ul class="subtask-menu-dropdown dropdown-menu dropdown-menu-end">
            <li class="d-flex justify-content-between align-items-center">

              <% if policy(subtask).edit? %>

                <%= link_to(edit_task_subtask_path(subtask.task_id, subtask.id),
                  data: {
                    turbo_frame: "edit_#{ dom_id subtask }_for_#{ dom_id subtask.task }"
                  },
                  class: "btn btn-xs btn-quarternary m-1",
                  title: "Edit this subtask"
                ) do %>

                  <i class="fa-solid fa-pen-to-square"></i>

                <% end %>

              <% end %>

              <a href="#" type="button"
                class="collapser btn btn-xs btn-success m-1"
                title="View subtask description"
                data-subtask-target="descBtn"
                data-bs-toggle="collapse"
                data-bs-target="#<%= dom_id subtask %>_description"
                aria-expanded="false"
                aria-controls="<%= dom_id subtask %>_description">

                <i data-subtask-target="descBtnIcon" class="fa-solid fa-chevron-down"></i>

              </a>

              <% if policy(subtask).destroy? %>

                <%= link_to(task_subtask_path(subtask.task_id, subtask.id),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },
                  class: "btn btn-xs btn-danger m-1",
                  title: "Delete this task?"
                ) do %>

                  <i class="fa-solid fa-trash"></i>

                <% end %>

              <% end %>

            </li>
          </ul>
        </div>

      </div>

    </div>
    <div id="<%= dom_id subtask %>_description"
      class="card-body p-0 collapse"
      data-subtask-target="descContainer"
      data-action="shown.bs.collapse->subtask#onDescOpen hidden.bs.collapse->subtask#onDescClose">

      <p class="card-text p-2"
        contenteditable="true"
        data-subtask-target="desc"
        data-action="focus->subtask#onDescFocus focusout->subtask#onDescLostFocus">

        <%= subtask.description %>

      </p>

    </div>
  </div>

<% end %>

app/views/tasks/_subtask_fields.html.erb
<div class="subtask-fields card m-1 p-2">
  <%= f.input :order,
    label: false,
    input_html: {
      class: "d-none"
    },
    wrapper_html: {
      class: "d-none m-0"
    } %>

  <%= f.input :title,
    label: false,
    placeholder: "Subtask title goes here...",
    input_html: {
      class: "form-control"
    } %>

  <%= f.input :description, as: :text,
    label: false,
    placeholder: "More detail here...",
    input_html: {
      class: "form-control mb-3",
      rows: 5,
      cols: 10
    } %>

  <%= f.input :comment, as: :text,
    label: false,
    placeholder: "Comment here...",
    input_html: {
      class: "d-none",
      rows: 5, cols: 10
    },
    wrapper_html: {
      class: "d-none m-0"
    } %>

  <%= f.input :ai_feedback, as: :text,
    label: false,
    placeholder: "AI Feedback here...",
    input_html: {
      class: "d-none",
      rows: 5, cols: 10
    },
    wrapper_html: {
      class: "d-none m-0"
    } %>

  <%= f.input :start_date, html5: true,
    label: false,
    input_html: {
      class: "form-control mb-3",
      value: f.object.start_date? ? f.object.start_date.strftime("%Y-%m-%d %H:%M") : "",
      min: Time.zone.now.strftime("%Y-%m-%d %H:%M"),
    } %>


  <%= f.input :duration, html5: true, as: :time,
    label: false,
    input_html: {
      class: "form-control mb-3",
      value: f.object.duration? ? f.object.duration_to_hms : "",
      step: 900,
    } %>

  <%= f.input :end_date, html5: true,
    label: false,
    input_html: {
      class: "d-none form-control",
      value: f.object.end_date? ? f.object.end_date.strftime("%Y-%m-%d %H:%M") : "",
      min: Time.zone.now.strftime("%Y-%m-%d %H:%M"),
    },
    wrapper_html: {
      class: "d-none m-0"
    } %>

  <%= f.input :completed, as: :boolean,
    label: false,
    input_html: {
      class: "d-none"
    },
    wrapper_html: {
      class: "d-none m-0"
    } %>

  <div class="subtask-controls d-flex justify-content-end align-items-center">

    <%= link_to_remove_nested(
      f,
      tag_attributes: {
          class: "remove-nested-assoc",
          title: "Remove this subtask"
        },
        link_classes: 'btn btn-sm btn-danger m-1',
        fields_wrapper_selector: '.subtask-fields'
      ) do %>

      <i class="fa-solid fa-trash"></i>

    <% end %>

  </div>
</div>

app/views/tasks/_task_card.html.erb
<%= turbo_frame_tag "edit_#{ dom_id task }",
  refresh: "morph",
  data: {
    sortable_target: 'dragable',
    controller: "task",
    task_sortable_outlet: "##{ turbo_frame_id }",
    task_subtask_outlet: ".subtask-of-#{ (dom_id task).gsub('_', '-') }",
    task_url_value: "#{ task_url task }",
    task_checked_value: task.completed,
    task_start_time_value: task.start_date.nil? ? "" : task.start_date.strftime("%H:%M"),
    task_start_date_time_value: task.start_date.nil? ? "" : task.start_date.strftime("%Y-%m-%d %H:%M"),
  },
  class: "dragable-item card task #{task.routine} #{task.task_type} parent-#{ (dom_id task).gsub('_', '-') } #{ task.completed ? ' card-checked' : '' }" do %>

  <div data-task-target="cardTitle" title="<%= task.start_date.nil? ? "" : task.start_date.strftime("%A %d %B %Y at %H:%M") %>">

    <div class="card-header d-flex justify-content-between align-items-center">

      <h3 class="card-title d-flex justify-content-between align-items-center flex-grow-1 overflow-fade">

        <i class="fa-solid fa-grip-vertical handle pe-2" data-action="mousedown->task#onHandleGrabbed"></i>

        <span id="<%= "#{dom_id task}_checkbox_wrapper" %>"
          class="checkbox-wrapper p-2"
          data-task-target="checkbox">

          <label
            data-task-target="fauxCheckbox"
            data-action="click->task#onCheckboxClicked"
            for="<%= "#{dom_id task}_completed" %>">

            <i data-task-target="fauxCheckIcon" class="fa-solid <%= task.completed ? "fa-square-check" : "fa-square" %>"></i>

          </label>

          <input id="<%= "#{dom_id task}_completed" %>"
            class="checkbox d-none"
            data-task-target="realCheckbox"
            type="checkbox"<%= task.completed ? " checked" : "" %>>

        </span>

        <span class="start-date-time pe-2">

          <input class="d-none" type="text"
            data-task-target="startDateTime"
            value="<%= task.start_date.nil? ? "" : task.start_date.strftime("%Y-%m-%d %H:%M") %>"
          />

          <span
            data-task-target="startTime"
            data-action="click->task#onStartTimeClick">

            <%= task.start_date.nil? ? "" : task.start_date.strftime("%H:%M") %>

          </span>

        </span>

        <span id="<%= "#{dom_id task}_title" %>"
          class="title-wrapper pe-2 flex-grow-1"
          contenteditable="true"
          data-task-target="title"
          data-action="focus->task#onTitleFocus focusout->task#onTitleLostFocus">

          <%= task.title %>

        </span>

      </h3>


      <div class="card-controls d-flex justify-content-end">

        <div class="btn-group">
          <button type="button" class="btn btn-secondary dropdown-toggle task-menu-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
            <i class="fa-solid fa-bars"></i>
          </button>
          <ul class="task-menu-dropdown dropdown-menu dropdown-menu-end">
            <li class="d-flex justify-content-between align-items-center">

              <%= link_to(new_task_subtask_path(task),
                data: {
                  turbo_frame: "new_subtask_for_#{ dom_id task }",
                  action: "task#doSubtasksOpenForNewSubtask"
                },
                class: "add-new-subtask btn btn-secondary m-1",
                title: "Add a subtask?"
              ) do %>

                <i class="fa-solid fa-square-plus"></i>

              <% end %>

              <% if policy(task).edit? %>

                <%= link_to(edit_task_path(task),
                  data: {
                    turbo_frame: "edit_#{ dom_id task }"
                  },
                  class: "btn btn-quarternary m-1",
                  title: "Edit this task"
                ) do %>

                  <i class="fa-solid fa-pen-to-square"></i>

                <% end %>

              <% end %>

              <a href="#" type="button"
                class="collapser btn btn-success m-1"
                title="View task description"
                data-bs-toggle="collapse"
                data-bs-target="#<%= dom_id task %>_description"
                data-task-target="descBtn"
                aria-expanded="false"
                aria-controls="<%= dom_id task %>_description">

                <i data-task-target="descBtnIcon" class="fa-solid fa-chevron-down"></i>

              </a>

              <a href="#" type="button"
                class="collapser btn btn-warning m-1"
                title="View all subtasks"
                data-bs-toggle="collapse"
                data-bs-target="#<%= dom_id task %>_subtasks"
                data-task-target="subtasksBtn"
                aria-expanded="false"
                aria-controls="<%= dom_id task %>_subtasks">

                <i data-task-target="subtasksBtnIcon" class="fa-solid fa-angles-down"></i>

              </a>

              <% if policy(task).destroy? %>

                <%= link_to(task_path(task),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },
                  class: "btn btn-danger m-1",
                  title: "Delete this task?"
                ) do %>

                  <i class="fa-solid fa-trash"></i>

                <% end %>

              <% end %>

            </li>
          </ul>
        </div>

      </div>

    </div>
    <div id="<%= dom_id task %>_description"
      class="card-body p-0 collapse"
      data-task-target="descContainer"
      data-action="shown.bs.collapse->task#onDescOpen hidden.bs.collapse->task#onDescClose">

      <p class="card-text p-2"
        contenteditable="true"
        data-task-target="desc"
        data-action="focus->task#onDescFocus focusout->task#onDescLostFocus">

        <%= task.description %>

      </p>

    </div>

    <div id="<%= dom_id task %>_subtasks"
      class="cards subtasks-container collapse-container collapse"
      data-action="shown.bs.collapse->task#onSubtasksOpen hidden.bs.collapse->task#onSubtasksClose"
      data-task-target="subtasksContainer">

      <%= turbo_frame_tag "new_subtask_for_#{ dom_id task }",
        data: {
          controller: 'sortable',
          sortable_subtask_outlet: ".subtask.subtask-of-#{ (dom_id task).gsub('_', '-') }",
          sortable_group_value: "new_subtask_for_#{ dom_id task }"
        },
        class: "subtasks-container" do %>

        <% if task.subtasks.length.positive? %>

          <% task.subtasks.each do |subtask| %>

            <%= render 'tasks/subtask_card', subtask: subtask %>

          <% end %>

        <% end %>

      <% end %>

    </div>

  </div>

<% end %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove "edit_#{ dom_id @task }" %>

app/views/tasks/index.html.erb
<main class="container-md">

  <dev class="col-md-12 p-md-3">

    <%= turbo_frame_tag "tasks_index_turbo_frame" do %>

      <div class="header d-flex justify-content-between align-items-center">

        <h1 class="my-5 mb-3 fst-bold">All Tasks</h1>

        <%= link_to new_task_path,
          data: {
            # turbo_frame: "new_task_turbo_frame"
            turbo_frame: @turbo_frame_id
          },
          class: "btn bg-quinary btn-lg",
          title: "Add a new task" do %>

          <i class="fa-solid fa-square-plus"></i>

        <% end %>

      </div>

    <% end %>

    <hr>

    <div id="all-tasks"
      class="cards tasks-container collapse-container">

      <%= turbo_frame_tag @turbo_frame_id,
        data: {
          controller: 'sortable',
          sortable_task_outlet: '.task',
          sortable_group_value: @turbo_frame_id
        } do %>

        <% @tasks.each_with_index do |task| %>

          <%= render 'task_card', task: task, turbo_frame_id: @turbo_frame_id %>

        <% end %>

      <% end %>

    </div>

  </div>

</main>