config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/daily-log", to: "logs#daily_log"
  get "/weekly-log", to: "logs#weekly_log"
  get "/monthly-log", to: "logs#monthly_log"
  get "/future-log", to: "logs#future_log"
  get "/users/profile", to: "pages#profile"
  get "/meet-the-team", to: "pages#meet_the_team"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks do
    resources :subtasks
  end
  resources :journal_entries, path: "journal-entries"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="animate-shadow alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="animate-shadow alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-5 bg-tertiary text-quarternary fs-5">


  <div class="container h-100 d-flex justify-content-between align-items-end">

      <div>

        <i class="animate-shadow fa-brands fa-square-facebook"></i>

        <i class="animate-shadow fa-brands fa-pinterest"></i>

        <i class="animate-shadow fa-brands fa-linkedin"></i>

        <i class="animate-shadow fa-brands fa-square-instagram"></i>

      </div>

      <div>

        <span class="animate-text-shadow copyright">

          <i class="fa-solid fa-scale-balanced"></i> Copyright &copy; MMXXIV - Marcus Aurelius

        </span>

      </div>

  </div>

</footer>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('');">

  <div class="container flex-column">

    <div class="banner d-flex justify-content-between align-items-center">
      <%# <%= image_tag('tsj-logo.svg', class: "rounded-5") %>
      <h1 class="animate__animated animate__fadeInUp animate__slow">
        <span class="display-1">The Stoic Journal</span>
        <hr>
        <span class="bd-font display-5 fst-italic">
          Accept what you cannot control.&nbsp;
          <span class="fst-normal">Focus</span> on what you can!
        </span>

        <a href="<%= daily_log_path %>" class="animate__animated animate__headShake animate__delay-2s animate__repeat-3 animate-inset-shadow fs-3 fw-bold btn bg-quinary btn-lg text-success">

          Start <span class="fst-italic">Your</span> Journey Today!

        </a>
      </h1>

    </div>

  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon sticky-top shadow-lg">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>

      <i class="fa-solid fa-building-columns"></i>

      <h5 class="d-inline-block bd-font mx-1">The Stoic Journal</h5>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Today", daily_log_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Weekly Log", weekly_log_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Monthly Log", monthly_log_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Future Log", future_log_path, class: "nav-link" %>
          </li>

          <% if false %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
          <% end %>

          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="<%= (current_user.image_url.length > 0 ? current_user.image_url : "https://kitt.lewagon.com/camps/1790") %>" class="avatar" alt="dropdown menu">
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "All Tasks", tasks_path, class: "dropdown-item" %>

              <hr>

              <%= link_to "Today's Log", daily_log_path, class: "dropdown-item" %>

              <%= link_to "Weekly Log", weekly_log_path, class: "dropdown-item" %>

              <%= link_to "Monthly Log", monthly_log_path, class: "dropdown-item" %>

              <%= link_to "Future Log", future_log_path, class: "dropdown-item" %>

              <hr>

              <% if false %>
              <%= link_to "Journal", journal_entries_path, class: "dropdown-item" %>
              <% end %>

              <%= link_to "Profile", users_profile_path, class: "dropdown-item" %>

              <% if false %>
              <%= link_to "Meet The Team", meet_the_team_path, class: "dropdown-item" %>
              <% end %>

              <hr class="my-2">

              <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">

            <%= link_to "Login?", new_user_session_path, class: "nav-link" %>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.orig.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>